apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker2048-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: game
          image: alexwhen/docker-2048:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
