apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: dev
  app: docker2048

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
     kind: Deployment
     name: docker2048-deployment