apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker2048-deployment
  labels:
    app: docker2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker2048
  template:
    metadata:
      labels:
        app: docker2048
    spec:
      containers:
        - name: game
          image: alexwhen/docker-2048:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
