apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker2048-deployment
  labels:
    app: docker2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker2048
  template:
    metadata:
      labels:
        app: docker2048
    spec:
      containers:
        - name: docker2048
          image: 471871787162.dkr.ecr.us-east-2.amazonaws.com/docker-2048:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80