# This is a basic workflow to help you get started with Actions
name: Testing Assume role action

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::471871787162:role/github-actions
          aws-region: us-east-2
      - name: Test AWS CLI
        run: |
          aws s3 ls
      
  
